# This is a basic workflow to help you get started with Actions

name: PR handler

on:
  issue_comment:
    types:
      - created

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'lgtm'}}
    steps:
      - name: Add label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['accepted-3']
            })
      - name: Close issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              stste: 'closed'
            })
      - name: Comment on issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR was closed by a bot. If this was a mistake, please re-open this issue and tag @pranavgade20'
            })
            
